---
- file:
    state: directory
    path: /tmp
- name: get script for install rbenv
  get_url:
    url: https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer 
    validate_certs: false
    dest: /tmp/install.sh
    mode: 0755
- name: install rbenv
  command: ./tmp/install.sh
- name: configre bash
  command: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc && echo 'eval "$(rbenv init -)"' >> ~/.bashrc && source ~/.bashrc


